### ISSUE TITLE
Suggested changes for publishing to hub.steampipe.io

### ISSUE THREAD

**Issue by e-gineer** [francois2metz/steampipe-plugin-scalingo#3]
Hi @francois2metz ... fantastic work on this plugin! It has come together well and worked great for me on first setup / try :-)

Here are some suggestions for changes before we publish it to the Steampipe Hub site. Happy to discuss if you have any questions.

Recommended changes:
* Table and column descriptions should be formal sentences including a period at the end. For example, `Type of the event.` (not `type of the event`).
* Whitespace in config/scalingo.spc should be cleaned up / aligned.
* Example token format should be updated to look like an actual token (clearer for the user).
* Most plugins will cache the connection object, avoiding extra setup time etc on each query. Depending on the API, many clients perform extra work (and even requests) during connection setup. Please see existing plugins for examples if you wish to do this, the plugin SDK provides helpers.
* Use [FromQual](https://pkg.go.dev/github.com/turbot/steampipe-plugin-sdk@v1.5.0/plugin/transform#FromQual) as an easy way to get passed in app_name value (instead of a [custom transform](https://github.com/francois2metz/steampipe-plugin-scalingo/blob/main/scalingo/utils.go#L43)).
* If the events table gets large, then adding support for limit checks can be helpful to improve performance and make it easier to run small sample queries ([example](https://github.com/turbot/steampipe-plugin-googleworkspace/blob/issue-10/googleworkspace/table_googleworkspace_drive_my_file.go#L411)).

Questions / surprising outcomes / should be fixed:
* Why does region list only return one region?

Hope this helps!

**Comment by francois2metz** [comment]
HI @e-gineer Thanks for your sugggestions!

I have done most of them except the last one, I need to think of a way to query more if needed.

About the regions, there is only 2 available regions right now on scalingo, but the second one (osc-secnum) is only available if you request it. I do have have an access and I successfully it.

**Comment by e-gineer** [comment]
ah - makes sense on the regions, I hadn’t enabled the second one.

Let us know if you have questions about the use of limit, happy to discuss. Not a blocker I don’t think, but makes a big difference if you have a lot of event data.

**Comment by francois2metz** [comment]
I'm looking to implement the limit features. Is there is a way to get the value of the limit parameter of the sql query? I think it is useful to be able to get old data if needed.

**Comment by e-gineer** [comment]
Yes! The limit from the query is available in the query context. Example:

https://github.com/turbot/steampipe-plugin-googleworkspace/blob/bd80b65f1557bacda41cc776608c3156070d6f80/googleworkspace/table_googleworkspace_drive_my_file.go#L413

**Comment by francois2metz** [comment]
I must be doing something wrong. I got a nil result. Let's try again.

**Comment by e-gineer** [comment]
oh? Happy to test out a branch of that will be helpful.

**Comment by francois2metz** [comment]
I just pushed the branch `limit`: https://github.com/francois2metz/steampipe-plugin-scalingo/compare/limit

**Comment by e-gineer** [comment]
I used the `limit` branch to do this query:
```
select * from scalingo_app_event where app_name = 'nw-test-01' limit 5
```

and am seeing the Limit coming through in the logs?
```
37213 2021-09-10 13:05:50.465 GMT [14614] LOG:  statement: select * from scalingo_app_event where app_name = 'nw-test-01' limit 5
37214 2021-09-10T09:05:50.468-0400 [WARN]  plugin.steampipe-plugin-scalingo.plugin: [WARN]  MaxResult: %!s(int64=5)=0xc003bfb738
```

So, looks like it is there to me?

**Comment by francois2metz** [comment]
Okay my bad. I tried with a `count(*)` query and the limit had no effects. Which makes senses I guess.

**Comment by francois2metz** [comment]
Thanks for your help. I have done everything on your list. I will apply some of theses suggestions to my others plugins ;).
